#!/bin/bash

# Volunteer App - Quick Start Setup Guide

echo "======================================="
echo "Volunteer App - Quick Setup Guide"
echo "======================================="
echo ""

# Step 1: Install dependencies
echo "Step 1: Installing dependencies..."
npm install

echo ""
echo "✅ Dependencies installed!"
echo ""
echo "======================================="
echo "Step 2: Firebase Configuration"
echo "======================================="
echo ""
echo "Please follow these steps to set up Firebase:"
echo ""
echo "1. Go to https://firebase.google.com"
echo "2. Create a new project"
echo "3. Go to Project Settings"
echo "4. Copy your Firebase config"
echo ""
echo "Then open firebaseConfig.js and replace:"
echo "  - apiKey: YOUR_API_KEY"
echo "  - authDomain: YOUR_AUTH_DOMAIN"
echo "  - projectId: YOUR_PROJECT_ID"
echo "  - storageBucket: YOUR_STORAGE_BUCKET"
echo "  - messagingSenderId: YOUR_MESSAGING_SENDER_ID"
echo "  - appId: YOUR_APP_ID"
echo ""
echo "5. Enable Firebase Authentication (Email/Password)"
echo "6. Create a Firestore Database (test mode)"
echo ""
echo "======================================="
echo "Step 3: Run the App"
echo "======================================="
echo ""
echo "Choose one:"
echo ""
echo "For WEB (easiest for testing):"
echo "  npm run web"
echo ""
echo "For ANDROID (requires Android Studio):"
echo "  npm run android"
echo ""
echo "For iOS (requires macOS):"
echo "  npm run ios"
echo ""
echo "Or use Expo Go App:"
echo "  npx expo start"
echo "  (Scan QR code with Expo Go app)"
echo ""
echo "======================================="
